name: LobbyPlugin
version: '${project.version}'
main: me.egorich.lobbyplugin.Main
api-version: 1.18

depend: [PlaceholderAPI]

commands:
  shutdown: {}
  permission:
    description: Команда для управления правами
    aliases:
      - pr
    usage: /pr {add|remove} (Имя игрока) (Имя права)

  vanish:
    description: Стать невидимым
    aliases:
      - vn
    usage: /vanish

  setbuilder:
    description: Добавить кого-то в групу строителей
    usage: /setbuilder (Имя игрока) {1|0}